# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Jn_qsPlKaa08kB1iJbK9NBbUyHGNBLlz
"""

import streamlit as st
import streamlit.components.v1 as components

st.set_page_config(
    page_title="Customer Retention Analysis",
    page_icon="📈",
    layout="wide"
)

st.title("📈 Customer Retention Analysis")
st.caption("Interactive Power BI Dashboard")

st.markdown("""
### Business Objective
Analyze customer retention, purchasing behavior, and customer segments to identify opportunities for improving customer loyalty and long-term business growth.

**Tools:** Python • SQL • Power BI

**Techniques:** Data Cleaning • EDA • Cohort Analysis • Customer Segmentation • K-Means Clustering
""")

st.divider()

components.iframe(
    "https://app.powerbi.com/view?r=eyJrIjoiZTA0MzgxNzktN2ViOC00Y2IzLTkxYTMtYzE5YzRjOWJjYmQ5IiwidCI6IjgyMTE5NTA1LTdmNTYtNGUxZC04NTlhLWJiZWFjODNhNzhhMCIsImMiOjEwfQ%3D%3D",
    width=1400,
    height=850,
    scrolling=True
)